# Extraindo informações estatícas sobre as turmas
Nesse seção iremos extrair informações estatiscas sobre as turmas, assim, teremos dados sobre componentes curriculasres, cursos, docentes, avaliação, etc.

In [1]:
import pandas as pd
import numpy as np

In [3]:
cursos = pd.read_csv("data/cursos-de-graduacao.csv", sep=';')

In [6]:
id_cet = 10320810

cursos[cursos.nome == 'CIÊNCIAS E TECNOLOGIA']

,id_curso,nome,id_coordenador,coordenador,situacao_curso,nivel_ensino,grau_academico,modalidade_educacao,area_conhecimento,tipo_oferta,...,campus,id_unidade_responsavel,unidade_responsavel,website,data_funcionamento,codigo_inep,dou,portaria_reconhecimento,convenio_academico,Unnamed: 22
15,10320810,CIÊNCIAS E TECNOLOGIA,5753080.0,KALINE MELO DE SOUTO VIANA,ATIVO,GRADUAÇÃO,BACHARELADO,Presencial,Ciências Exatas e da Terra,Regular,...,NaN,4885,ESCOLA DE CIÊNCIAS E TECNOLOGIA,http://www.prograd.ufrn.br,NaN,116756.0,2014-03-31,Portaria nº 217/2014 - DIREG/MEC,NaN,NaN

In [11]:
# importando estrutura curriculas
estrutura = pd.read_csv("data/estruturas-curriculares.csv", sep=";")

In [16]:
estrutura[estrutura.id_curso == id_cet]

,id_curriculo,codigo,nome_matriz,id_curso,nome_curso,semestre_conclusao_minimo,semestre_conclusao_ideal,semestre_conclusao_maximo,meses_conclusao_minimo,meses_conclusao_ideal,...,cr_minimo_semestre,cr_ideal_semestre,cr_maximo_semestre,ch_minima_semestre,ch_ideal_semestre,ch_maxima_semestre,periodo_entrada_vigor,ano_entrada_vigor,observacao,Unnamed: 28
98,107405230,02,CIÊNCIAS E TECNOLOGIA - NATAL - MT - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,6.0,6.0,9.0,NaN,NaN,...,180.0,420.0,480.0,180.0,NaN,0.0,1,2015,NaN,NaN
136,115765126,02,CIÊNCIAS E TECNOLOGIA - NATAL - MT - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,6.0,6.0,10.0,NaN,NaN,...,4.0,24.0,32.0,60.0,NaN,420.0,1,2016,NaN,NaN
244,115305512,02,CIÊNCIAS E TECNOLOGIA - NATAL - MT - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,10.0,NaN,NaN,...,4.0,24.0,42.0,60.0,NaN,0.0,1,2016,NaN,NaN
264,115306301,02,CIÊNCIAS E TECNOLOGIA - NATAL - N - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,11.0,NaN,NaN,...,4.0,24.0,42.0,60.0,NaN,0.0,1,2016,NaN,NaN
271,107405556,02,CIÊNCIAS E TECNOLOGIA - NATAL - N - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,10.0,NaN,NaN,...,4.0,24.0,32.0,120.0,NaN,0.0,1,2015,NaN,NaN
273,115307035,02,CIÊNCIAS E TECNOLOGIA - NATAL - N - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,11.0,NaN,NaN,...,4.0,24.0,42.0,60.0,NaN,0.0,1,2016,NaN,NaN
275,115803290,02,CIÊNCIAS E TECNOLOGIA - NATAL - MTN - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,5.0,7.0,9.0,NaN,NaN,...,4.0,24.0,32.0,60.0,NaN,0.0,1,2016,NaN,NaN
276,115272412,02,CIÊNCIAS E TECNOLOGIA - NATAL - N - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,11.0,NaN,NaN,...,4.0,7.0,32.0,60.0,NaN,0.0,1,2016,NaN,NaN
277,115273212,02,CIÊNCIAS E TECNOLOGIA - NATAL - T - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,6.0,6.0,10.0,NaN,NaN,...,4.0,24.0,32.0,60.0,NaN,0.0,1,2016,NaN,NaN
289,115306807,02,CIÊNCIAS E TECNOLOGIA - NATAL - MT - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,10.0,NaN,NaN,...,4.0,24.0,42.0,60.0,NaN,0.0,1,2016,NaN,NaN
299,115764587,02,CIÊNCIAS E TECNOLOGIA - NATAL - N - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,7.0,7.0,11.0,NaN,NaN,...,4.0,24.0,32.0,60.0,NaN,0.0,1,2016,NaN,NaN
310,115802434,02,CIÊNCIAS E TECNOLOGIA - NATAL - MT - BACHARELADO,10320810,CIÊNCIAS E TECNOLOGIA,5.0,7.0,9.0,NaN,NaN,...,4.0,24.0,32.0,60.0,NaN,0.0,1,2016,NaN,NaN

In [9]:
curriculo = pd.read_csv("data/curriculo-componente-graduacao.csv", sep=";")

In [18]:
curriculo_cet = curriculo[curriculo.id_curriculo == 115802434]

In [28]:
# importando dados do componente curriculas
disciplinas = pd.read_csv("data/componentes-curriculares-presenciais-ok.csv")
disciplinas.iloc[:, ]

In [31]:
disciplinas_cet = disciplinas[disciplinas.id_componente.isin(curriculo_cet.id_componente_curricular)]

In [47]:
cols = ['id_componente', 'tipo_componente', 'codigo', 'nome', 'unidade_responsavel', 'ementa', \
       'bibliografia', 'objetivos', 'conteudo']

disciplinas_cet = disciplinas_cet[cols]

In [50]:
disciplinas_cet.head()

,id_componente,tipo_componente,codigo,nome,unidade_responsavel,ementa,bibliografia,objetivos,conteudo
216,20029,DISCIPLINA,DCA0414,INTRODUCAO A ROBOTICA,DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUT...,REPRESENTAÇÃO MATEMÁTICA DE POSIÇÃO E ORIEN...,NaN,1. Robótica: conceitos básicos. 1.1. Robôs man...,1. Robótica: conceitos básicos. 1.1. Robôs man...
11004,40107,DISCIPLINA,DCA0103,ANALISE DE SINAIS E SISTEMAS,DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUT...,Introdução aos sinais e sistemas lineares. Equ...,NaN,"Após a conclusão da disciplina, o aluno deverá...",Introdução Definições Classificação de sinais ...
11005,40108,DISCIPLINA,DCA0104,ARQUITETURA DE COMPUTADORES,DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUT...,Introdução à arquitetura de computadores. Arqu...,NaN,Evolução das arquiteturas de computadores. Com...,Introdução Arquitetura de Computadores Evoluçã...
11006,40109,DISCIPLINA,DCA0105,TEORIA DE CIRCUITOS,DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUT...,Classificação e componentes de circuitos. Leis...,NaN,Classificação dos circuitos. Componentes de ci...,Introdução Grandezas de circuitos elétricos: t...
11011,40114,DISCIPLINA,DCA0110,MODELAGEM E ANALISE DE SISTEMAS DINAMICOS,DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUT...,Aspectos gerais da teoria de controle. Lineari...,NaN,Aspectos gerais da teoria de controle. Lineari...,Introdução aos problemas de controle. Nomencla...

In [53]:
disciplinas_cet.to_csv('outputs/displicinas_cet.csv', sep=';', index_label=False)