# Mesclando os dados de Matrículas, Turmas e Disciplinas
## Objetivo
Esse notebook visa pegar informações que relacionam turmas, matrículas e disciplinas para facilitar 
a visualização dos dados.

In [1]:
import pandas as pd

In [2]:
matr = pd.read_csv("data/outputs/matriculas_cet_20172.csv", sep=';')
disciplinas = pd.read_csv("data/componentes-curriculares-presenciais-ok.csv", index_col=0)
turmas = pd.read_csv("data/turmas-20172.csv", sep=";")

In [3]:
matr.head()

,id_turma,discente,id_curso,media_final,numero_total_faltas,descricao
0,57603646,c119d334d6c55121d48dc7f5d43bbe1f,10320810.0,8.2,4.0,APROVADO
1,57603630,30156bac31160066c22688ccc9fa1287,10320810.0,1.0,48.0,REPROVADO POR MÉDIA E POR FALTAS
2,57603630,7c8756bfafd6623effbeefe83ac2ea15,10320810.0,7.0,4.0,APROVADO
3,57603833,972c641f5303e93483e5c318ef19e0cd,10320810.0,7.3,0.0,APROVADO
4,57606520,e0830e6363b8c6a692d3aea55eab73c1,10320810.0,5.0,0.0,APROVADO POR NOTA

In [4]:
disciplinas.head()

,id_componente,tipo_componente,codigo,nivel,nome,unidade_responsavel,ch_teorico,ch_pratico,ch_estagio,ch_total,...,ementa,bibliografia,objetivos,conteudo,competencias_habilidades,referencias,ano_programa,periodo_programa,modalidade,curso_componente
0,18643,DISCIPLINA,MUT508,T,COMPOSIÇÃO EM MÚSICA POPULAR III,ESCOLA DE MÚSICA,60,0,0,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,NaN
1,18644,DISCIPLINA,MUT516,T,CO-REPETIÇÃO,ESCOLA DE MÚSICA,30,0,0,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,NaN
2,18645,DISCIPLINA,MUT520,T,CONTRABAIXO ACÚSTICO I,ESCOLA DE MÚSICA,30,0,0,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,NaN
3,18646,DISCIPLINA,MUT165,T,PIANO COMPLEMENTAR I,ESCOLA DE MÚSICA,15,0,0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,NaN
4,18647,DISCIPLINA,MUT167,T,PIANO COMPLEMENTAR III,ESCOLA DE MÚSICA,15,0,0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Presencial,NaN

In [5]:
turmas.head(2)

,id_turma,codigo_turma,id_docente_interno,id_docente_externo,observacao,id_componente_curricular,nivel_ensino,campus_turma,local,ano,...,tipo,distancia,data_consolidacao,agrupadora,id_turma_agrupadora,qtd_aulas_lancadas,situacao_turma,convenio,modalidade_participantes,Unnamed: 25
0,57602445,01,NaN,120983811.0,NaN,63499,LATO SENSU,NaN,Auditório do DEF e LabLUD do DEF da UFRN,2017,...,REGULAR,f,2017-10-30 16:56:59.858,f,NaN,15.0,CONSOLIDADA,NaN,Presencial,NaN
1,57602445,01,5755233.0,NaN,NaN,63499,LATO SENSU,NaN,Auditório do DEF e LabLUD do DEF da UFRN,2017,...,REGULAR,f,2017-10-30 16:56:59.858,f,NaN,15.0,CONSOLIDADA,NaN,Presencial,NaN

## Pegando só as colunas desejadas

In [6]:
cols = ['id_turma', 'id_componente_curricular', 'ano', 'periodo']
turmas = turmas[cols]

In [12]:
cols = ['id_componente', 'codigo', 'nome', 'curso_componente']
disciplinas = disciplinas[cols]
disciplinas = disciplinas.rename(index=str, columns={'id_componente': 'id_componente_curricular'})

## Realizando merge de Matriculas e Turmas

In [8]:
matr.shape

(15275, 6)

In [9]:
matriculas = matr.merge(turmas, how='left', left_on='id_turma', right_on='id_turma')
matriculas.shape

(17471, 9)

In [10]:
matriculas = matriculas.drop_duplicates()
matriculas.shape

(15275, 9)

## Realizando merge de Matriculas e Disciplinas

In [13]:
matr_ect = matriculas.merge(disciplinas, how='left', left_on='id_componente_curricular', right_on='id_componente', )
matr_ect.shape

KeyError: 'id_componente'

In [67]:
matr_ect.head()

,id_turma,discente,id_curso,media_final,numero_total_faltas,descricao,id_componente_curricular,ano,periodo,id_componente,codigo,nome,curso_componente
0,57603646,c119d334d6c55121d48dc7f5d43bbe1f,10320810.0,8.2,4.0,APROVADO,25009,2017,2,25009,DEF0152,CULTURA POPULAR,NaN
1,57603630,30156bac31160066c22688ccc9fa1287,10320810.0,1.0,48.0,REPROVADO POR MÉDIA E POR FALTAS,25025,2017,2,25025,DEF0054,METODOLOGIA DO ATLETISMO,NaN
2,57603630,7c8756bfafd6623effbeefe83ac2ea15,10320810.0,7.0,4.0,APROVADO,25025,2017,2,25025,DEF0054,METODOLOGIA DO ATLETISMO,NaN
3,57603833,972c641f5303e93483e5c318ef19e0cd,10320810.0,7.3,0.0,APROVADO,25042,2017,2,25042,DEF0051,METODOLOGIA DO FUTSAL,NaN
4,57606520,e0830e6363b8c6a692d3aea55eab73c1,10320810.0,5.0,0.0,APROVADO POR NOTA,25455,2017,2,25455,ELE0500,INTRODUCAO A ENGENHARIA ELETRICA,NaN

In [54]:
# matr_ect.groupby('nome')['nome'].count().sort_values(ascending=False)[120:]

## Exportando os dados

In [68]:
matr_ect.to_csv("data/outputs/matr_final_20172.csv", sep=";", index=False)